// aruco_ids.h — auto-generated by gen_aruco.py
// Include in aruco_obs.hpp and main.cpp
#pragma once

// Marker ID → Overcooked channel mapping
#define ARUCO_ID_PLAYER_1      0
#define ARUCO_ID_PLAYER_2      1
#define ARUCO_ID_WALL          2
#define ARUCO_ID_FLOOR         3
#define ARUCO_ID_ONION         4
#define ARUCO_ID_TOMATO        5
#define ARUCO_ID_DISH          6
#define ARUCO_ID_SOUP          7
#define ARUCO_ID_POT           8
#define ARUCO_ID_SERVE         9
#define ARUCO_ID_DELIVERY     10

// Channel indices (must match CHANNELS dict in Python training code)
#define CH_WALL      0
#define CH_FLOOR     1
#define CH_SELF      2
#define CH_TEAMMATE  3
#define CH_ONION     4
#define CH_TOMATO    5
#define CH_DISH      6
#define CH_SOUP      7
#define CH_POT       8
#define CH_SERVE     9
#define CH_DELIVERY 10
