"""
gen_aruco.py
============
Generates ArUco markers (DICT_4X4_50) for every Overcooked-AI component
plus the two robot agents, and assembles a print-ready A4 PDF sheet.

Marker ID map
─────────────
 0  player_1    (SELF)
 1  player_2    (TEAMMATE)
 2  wall
 3  floor
 4  onion
 5  tomato
 6  dish
 7  soup
 8  pot
 9  serve       (serving counter)
10  delivery    (delivery zone)

The same IDs must be used in aruco_obs.hpp:
    #define ARUCO_ID_SELF     0
    #define ARUCO_ID_TEAMMATE 1
"""

import cv2
import numpy as np
from pathlib import Path

# ── Component → marker ID mapping ────────────────────────────────────────────
COMPONENTS = {
    "player_1":  0,   # SELF      → CH_SELF
    "player_2":  1,   # TEAMMATE  → CH_TEAMMATE
    "wall":      2,   # CH_WALL
    "floor":     3,   # CH_FLOOR
    "onion":     4,   # CH_ONION
    "tomato":    5,   # CH_TOMATO
    "dish":      6,   # CH_DISH
    "soup":      7,   # CH_SOUP
    "pot":       8,   # CH_POT
    "serve":     9,   # CH_SERVE
    "delivery": 10,   # CH_DELIVERY
}

# Colors for label backgrounds (BGR)
LABEL_COLORS = {
    "player_1":  (200,  80,  40),
    "player_2":  ( 40, 160, 200),
    "wall":      ( 60,  60,  60),
    "floor":     (180, 180, 180),
    "onion":     ( 60, 200, 200),
    "tomato":    ( 40,  40, 220),
    "dish":      (220, 200,  60),
    "soup":      ( 40, 180, 100),
    "pot":       (100, 100, 160),
    "serve":     (180,  80, 180),
    "delivery":  ( 80, 200, 100),
}

# ── Output settings ───────────────────────────────────────────────────────────
MARKER_PX       = 200          # marker image size (px)
BORDER_BITS     = 1            # quiet-zone border in modules
OUTPUT_DIR      = Path("aruco_markers")
SHEET_COLS      = 3            # markers per row on the print sheet
MARKER_PRINT_MM = 60           # printed size per marker (mm)
DPI             = 300
PX_PER_MM       = DPI / 25.4


def generate_marker(aruco_dict, marker_id: int, size_px: int) -> np.ndarray:
    """Return a grayscale marker image (size_px × size_px)."""
    img = np.zeros((size_px, size_px), dtype=np.uint8)
    cv2.aruco.generateImageMarker(aruco_dict, marker_id, size_px, img, BORDER_BITS)
    return img


def add_label(marker_img: np.ndarray, name: str, marker_id: int,
              color_bgr=(80, 80, 80)) -> np.ndarray:
    """
    Attach a label strip below the marker with the component name and ID.
    Returns a new BGR image with the label appended.
    """
    H, W = marker_img.shape[:2]
    LABEL_H = 52
    canvas = np.ones((H + LABEL_H, W, 3), dtype=np.uint8) * 255

    # Paste marker (convert to BGR)
    marker_bgr = cv2.cvtColor(marker_img, cv2.COLOR_GRAY2BGR)
    canvas[:H, :W] = marker_bgr

    # Label background
    cv2.rectangle(canvas, (0, H), (W, H + LABEL_H), color_bgr, -1)

    # Component name
    font     = cv2.FONT_HERSHEY_DUPLEX
    name_str = name.upper().replace("_", " ")
    id_str   = f"ID: {marker_id:02d}"

    for text, y, scale, thick in [
        (name_str, H + 22, 0.62, 1),
        (id_str,   H + 42, 0.50, 1),
    ]:
        (tw, _), _ = cv2.getTextSize(text, font, scale, thick)
        x = (W - tw) // 2
        cv2.putText(canvas, text, (x, y), font, scale, (255, 255, 255), thick, cv2.LINE_AA)

    return canvas


def build_print_sheet(labeled_imgs: list, cols: int, gap_px: int = 20) -> np.ndarray:
    """Tile labeled marker images into a white sheet."""
    rows = (len(labeled_imgs) + cols - 1) // cols
    H, W = labeled_imgs[0].shape[:2]
    sheet_h = rows * H + (rows + 1) * gap_px
    sheet_w = cols * W + (cols + 1) * gap_px
    sheet = np.ones((sheet_h, sheet_w, 3), dtype=np.uint8) * 245  # off-white

    for idx, img in enumerate(labeled_imgs):
        row, col = divmod(idx, cols)
        y0 = gap_px + row * (H + gap_px)
        x0 = gap_px + col * (W + gap_px)
        sheet[y0:y0+H, x0:x0+W] = img

    return sheet


def save_header(components: dict, output_dir: Path):
    """Write a C header with the marker ID definitions."""
    lines = [
        "// aruco_ids.h — auto-generated by gen_aruco.py",
        "// Include in aruco_obs.hpp and main.cpp",
        "#pragma once",
        "",
        "// Marker ID → Overcooked channel mapping",
    ]
    for name, mid in components.items():
        lines.append(f"#define ARUCO_ID_{name.upper():<12} {mid:2d}")

    lines += [
        "",
        "// Channel indices (must match CHANNELS dict in Python training code)",
        "#define CH_WALL      0",
        "#define CH_FLOOR     1",
        "#define CH_SELF      2",
        "#define CH_TEAMMATE  3",
        "#define CH_ONION     4",
        "#define CH_TOMATO    5",
        "#define CH_DISH      6",
        "#define CH_SOUP      7",
        "#define CH_POT       8",
        "#define CH_SERVE     9",
        "#define CH_DELIVERY 10",
    ]

    header_path = output_dir / "aruco_ids.h"
    header_path.write_text("\n".join(lines) + "\n")
    print(f"  Saved C header → {header_path}")


def main():
    OUTPUT_DIR.mkdir(exist_ok=True)
    aruco_dict = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_4X4_50)

    labeled_imgs = []
    print("Generating markers…")

    for name, mid in COMPONENTS.items():
        # Raw marker
        marker = generate_marker(aruco_dict, mid, MARKER_PX)

        # Save raw PNG
        raw_path = OUTPUT_DIR / f"{mid:02d}_{name}_raw.png"
        cv2.imwrite(str(raw_path), marker)

        # Labeled version
        color = LABEL_COLORS.get(name, (80, 80, 80))
        labeled = add_label(marker, name, mid, color)
        lbl_path = OUTPUT_DIR / f"{mid:02d}_{name}.png"
        cv2.imwrite(str(lbl_path), labeled)
        labeled_imgs.append(labeled)

        print(f"  [{mid:02d}] {name:<12} → {lbl_path.name}")

    # Print sheet
    sheet = build_print_sheet(labeled_imgs, cols=SHEET_COLS, gap_px=24)
    sheet_path = OUTPUT_DIR / "print_sheet.png"
    cv2.imwrite(str(sheet_path), sheet)
    print(f"\nPrint sheet → {sheet_path}  ({sheet.shape[1]}×{sheet.shape[0]} px)")

    # C header
    save_header(COMPONENTS, OUTPUT_DIR)

    # Summary
    print("\n── Marker ID Summary ─────────────────────────────────────────────")
    print(f"  Dictionary  : DICT_4X4_50")
    print(f"  Border bits : {BORDER_BITS}")
    print(f"  Image size  : {MARKER_PX}×{MARKER_PX} px")
    print(f"  Print size  : ~{MARKER_PRINT_MM} mm  (scale to taste)")
    print()
    print(f"  {'Name':<14}  ID   Channel")
    print(f"  {'─'*14}  ──   ───────")
    ch_map = {v: k for k, v in {
        "wall":0,"floor":1,"player_1":2,"player_2":3,
        "onion":4,"tomato":5,"dish":6,"soup":7,
        "pot":8,"serve":9,"delivery":10
    }.items()}
    for name, mid in COMPONENTS.items():
        ch_name = name if name.startswith("player") else name
        print(f"  {name:<14}  {mid:02d}   CH_{ch_name.upper()}")
    print()
    print("Done. Files in:", OUTPUT_DIR.resolve())


if __name__ == "__main__":
    main()
